RestToCode: first pull
bjones1/CodeChat pull request #5
Opened 2017-05-24 11:50 UTC by acmitchell11

This specific version is so that you can look at and test the code since my pytest is doing weird things. Do not actually merge yet because this is unfinished. I tried installing the 64 bit version of python (uninstalled 32 bit) and pytest worked one time. It then resumed giving me the same errors. They are OS errors, and I just installed the newest Windows update. This might be the cause of the new errors. Also, on the test that actually worked, I tested some of the files in CodeChat to insure round trip stability of the file interpreters. CodeChat.css was interpreted by code_to_rest_file as 'CSS+Lasso' as the correct lexer. This made the test fail with a Key Error because we do not support 'CSS+Lasso'. I have no idea why it was allowed to suggest this lexer, and it might have been a one time error. Replicating this error might be helpful in finding a bug in the code.

2017-06-09 21:43 UTC, acmitchell11 commented
I also got Pytest to stop throwing the OS Windows 87 error. It turns out that I just needed to uninstall Python 3.6 and use 3.5 instead. I don't know why, but I think that one of the dependencies has trouble operating in 3.6

2017-06-09 23:16 UTC, bjones1 commented
Awesome. Nice job debugging. Not sure why.

2017-06-14 15:25 UTC, bjones1 requested changes

2017-06-29 14:25 UTC, acmitchell11 commented on CodeChat/CodeToRest.py
> +    options.setdefault('tabsize',4)
Done

2017-06-29 14:26 UTC, acmitchell11 commented on CodeChat/CommentDelimiterInfo.py
> +  # PODs not supported. Only single line comments
Done

2017-06-29 14:39 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +    # TODO Make a test for finding the file extention.
Done

2017-06-29 14:39 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +# |
Done

2017-06-29 14:41 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +def file_info(
Taken out

2017-06-29 14:41 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +    elif is_block_comment is True and comment_type[1] is False:
Done

2017-06-29 14:41 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +        return formulate_inline_comment(line, comment_delimiters) # TODO create a test to check if this is right... I think it might only do the first line of the block comment and skip the rest.
Done

2017-06-29 14:41 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +def formulate_inline_comment(
Done

2017-06-29 14:42 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +    f = '{} '.format(comment_delimiters[0]) + line + '\n'
Done

2017-06-29 14:42 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +        f = '{} '.format(comment_delimiters[1]) + line + '{}'.format(comment_delimiters[2]) + '\n'
Done

2017-06-29 14:57 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +  source_rst_path=None,
Got rid of the default value

2017-06-29 14:58 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +  out_path=None,
Added the comment and code for this to work

2017-06-29 14:59 UTC, acmitchell11 commented on CodeChat/RestToCode.py
> +        if source_rst_path is None:
Changed this part of the code entirely, so this is fixed

2017-06-29 15:03 UTC, acmitchell11 commented
All requested changes are completed and uploaded. You should be able to see them.

2017-07-26 16:16 UTC, merged